### ISSUE TITLE
Polyline extrusion direction not set

### ISSUE THREAD

**Issue by Serthys** [gdsestimating/dxf-parser#39] opened 2018-09-23 14:39 UTC
On 
https://github.com/gdsestimating/dxf-parser/blob/master/lib/entities/polyline.js#L44 and on dist 
https://github.com/gdsestimating/dxf-parser/blob/master/dist/dxf-parser.js#L1979.

Is that intended or a mistake?

**Comment by bzuillsmith** [comment] 2019-02-12 23:45
Somehow never saw this. Those source files have changed now. Was it just an inconsistency between the source and dist? I see line 42 of polyline.js has an extrusionDirection...

**Comment by bzuillsmith** [comment] 2019-02-13 19:56
Actually, I see from a PR what the problem is. Should have been ```entity.extrusionDirection = ...``` I'll get that merged in soon and publish

**Closed** 2020-04-14 18:41 UTC
